Update PutRecipe for new Git infrastructure.

diff --git a/bin/ImportRecipe b/bin/ImportRecipe
--- a/bin/ImportRecipe
+++ b/bin/ImportRecipe
@@ -5,7 +5,7 @@
 source ScriptFunctions
 Import GoboLinux
 Import File
-Import Subversion
+Import Git
 Import OptionParser
 Import Archive
 
@@ -28,8 +28,9 @@ Parse_Options "$@"
 # ${goboUserSettings}/Scripts/INSERT_NAME_HERE.conf 
 
 Parse_Conf Compile/Compile.conf
-Parse_Conf --mandatory CompileSubversion.conf
-[ -z "${compileSubversionLocalDir}" ] && Die "You must run 'UpdateSettings develscripts' before trying to run ImportRecipe again."
+Parse_Conf --mandatory CompileGit.conf
+[ "$compileGitServerRepository" ] || Die "Please check your CompileGit.conf configuration."
+
 ### Cleanup ###################################################################
 
 trap do_cleanup EXIT
@@ -61,12 +62,12 @@ if [ "$revision" ]
 then Die "A recipe submitted to the trunk should not have a revision. Not adding it."
 fi
 
-if [ -d ${compileSubversionLocalDir} ]
+if [ -d ${compileGitLocalDir} ]
 then
-   Quiet mkdir -p ${compileSubversionLocalTrunk}
-   Quiet mkdir -p ${compileSubversionLocalRevisions}
-   [ -w ${compileSubversionLocalTrunk} ] || Die "Need write permissions to ${compileSubversionLocalTrunk}."
-   [ -w ${compileSubversionLocalRevisions} ] || Die "Need write permissions to ${compileSubversionLocalRevisions}."
+   Quiet mkdir -p ${compileGitLocalTrunk}
+   Quiet mkdir -p ${compileGitLocalRevisions}
+   [ -w ${compileGitLocalTrunk} ] || Die "Need write permissions to ${compileGitLocalTrunk}."
+   [ -w ${compileGitLocalRevisions} ] || Die "Need write permissions to ${compileGitLocalRevisions}."
 else
    [ -w $compileDir ] || Die "Need write permissions to $compileDir."
 fi
@@ -85,33 +86,9 @@ fi
 
 ### Find a basis recipe in trunk ##############################################
 
-unset checkedout
-if ! trunk=`Get_Local_Trunk`
-then 
-   if Boolean batch || Ask "You don't seem to have a copy of the svn trunk tree. Fetch it?"
-   then
-      Log_Normal "Calling 'svn checkout'."
-      mkdir -p ${compileSubversionLocalDir}
-      Quiet pushd ${compileSubversionLocalDir}
-      svn checkout --non-recursive $compileSubversionServerRepository/trunk || Die "Error doing the svn checkout."
-      Quiet popd
-      Log_Normal "Checkout finished."
-      checkedout=yes
-   fi
-   if ! trunk=`Get_Local_Trunk` || [ ! "$checkedout" ]
-   then Die "Could not find a valid svn trunk."
-   fi
-fi
+Check_Git_Tree || Die "Failed checking git tree."
 
-existingprogram=`ls "$trunk" 2> /dev/null | grep -i "^$program$"`
-if [ ! "$existingprogram" ]
-then
-   Log_Normal "Trying to checkout $program..."
-   Quiet pushd $trunk
-   svn checkout "$compileSubversionServerRepository/trunk/$program"
-   Quiet popd
-   checkedout=yes
-fi
+trunk=`Get_Local_Trunk`
 
 existingprogram=`ls "$trunk" 2> /dev/null | grep -i "^$program$"`
 if [ "$existingprogram" ]
@@ -125,12 +102,6 @@ then
       program="$existingprogram"
    fi
 
-   if [ ! "$checkedout" ]
-   then
-      Log_Normal "Updating local subversion copy..."
-      svn update "$trunk/$program"
-   fi
-
    oldrecipedir=$(GuessLatest $trunk/$program/*)
    newrecipedir="$trunk/$program/$version"
    unpackrecipedir="$unpackdir/$program/$version"
@@ -140,11 +111,11 @@ then
 
    if [ "$latestexisting" = "$version" ]
    then
-      diff -Naur --exclude=".svn" "$oldrecipedir" "$unpackrecipedir" >& /dev/null
+      diff -Naur "$oldrecipedir" "$unpackrecipedir" >& /dev/null
       if [ $? = 0 ]
       then
          Log_Terse "Version in trunk matches exactly with the given recipe"
-         exit 0
+         exit 1
       fi
       Log_Terse "Latest version in trunk is already $version."
       Boolean batch || Ask_Continue "Will display differences."
@@ -154,49 +125,34 @@ then
    then
       Boolean batch || Ask_Continue "Latest version in trunk ($latestexisting) seems more recent than recipe ($version). Add $version to trunk anyway?"
    fi
-   
-   # Create newrecipedir if it's a new version
 
-   if [ "$oldrecipedir" != "$newrecipedir" -a ! -d "$newrecipedir" ]
-   then
-      svn copy "$oldrecipedir" "$newrecipedir" || Die "Failed preparing new version in trunk. Please check."
-   fi
-
-   # Update newrecipedir to match contents of unpackrecipedir:
-
-   ( cd "$newrecipedir"; find . | tac | grep -v "\.svn" ) | while read entry
-   do
-      if [ ! -e "$unpackrecipedir/$entry" ]
-      then
-         svn remove "$newrecipedir/$entry"
-      fi
-   done | sort -u
-   
+   mkdir -p "$newrecipedir"
    cp -af "$unpackrecipedir"/* "$newrecipedir"
-   
-   Subversion_Status_Match "?" "$newrecipedir" | while read entry
-   do
-      svn add "$entry"
-   done
+
+   Quiet pushd "${compileGitLocalTrunk}"
+   git add "$newrecipedir"
 
    if [ $latestexisting != $version ] && { Boolean batch || Ask "View differences in new version?" ; }
-   then Subversion_Diff "$newrecipedir"
+   then diff -Naur "$oldrecipedir" "$unpackrecipedir" | mtail --config="$goboSettings/Scripts/diff.mtailrc" | less -R
    fi
-
-   # Exhibit a status summary for copy-n-paste convenience
-   Log_Normal "Summary of differences:"
-   Subversion_Status "$newrecipedir"
+   Quiet popd
 else
    Log_Terse "No existing versions for $program were found."
    Boolean batch || Ask_Continue "Add new program $program to the recipes trunk?"
    cp -af "$unpackdir/$program" "$trunk"
-   svn add "$trunk/$program"
+   Quiet pushd "${compileGitLocalTrunk}"
+   git add "$trunk/$program"
    if Boolean batch || Ask "View contents of new entry in trunk?"
-   then Subversion_Diff "$trunk/$program"
+   then find "$trunk/$program"
    fi
-   # Exhibit a status summary for copy-n-paste convenience
-   Log_Normal "Summary of addition:"
-   Subversion_Status "$trunk/$program"
+   Quiet popd
 fi
 
+Quiet pushd ${compileGitLocalTrunk}
+# Exhibit a status summary for copy-n-paste convenience
+Log_Normal "Summary of addition:"
+git status
+git commit -m "$program $version submitted by $compileRecipeAuthor"
+Quiet popd
+   
 exit 0
diff --git a/bin/PublishRevision b/bin/PublishRevision
--- a/bin/PublishRevision
+++ b/bin/PublishRevision
@@ -5,7 +5,7 @@
 source ScriptFunctions
 Import GoboLinux
 Import File
-Import Subversion
+Import Git
 Import OptionParser
 
 ### Options ###################################################################
@@ -29,8 +29,8 @@ Parse_Options "$@"
 # ${goboUserSettings}/Scripts/INSERT_NAME_HERE.conf 
 
 Parse_Conf Compile/Compile.conf
-Parse_Conf CompileSubversion.conf
-[ -z "${compileSubversionLocalDir}" ] && Die "You must run 'UpdateSettings develscripts' before trying to run PublishRevision again."
+Parse_Conf --mandatory CompileGit.conf
+[ "$compileGitServerRepository" ] || Die "Please check your CompileGit.conf configuration."
 
 unset batch
 Boolean "batch" && batch=yes
@@ -40,13 +40,43 @@ username=`Entry username`
 
 ### Operation #################################################################
 
+# 0 - publish directly
+# 1 - ask for confirmation
+# 2 - abort
+function lint_recipe() {
+   program="$1"
+   version="$2"
+   
+   recipetarball="$goboTemp/$program--$version--recipe.tar.bz2"
+   (
+      cd "$trunk"
+      Verbose tar cjvpf "$recipetarball" "$program/$version"
+   )
+   RecipeLint "$recipetarball"
+   status=$?
+   rm "$recipetarball"
+   if [ "$status" -eq 1 ]
+   then
+      Log_Error "RecipeLint reported warnings in $program $version from trunk."
+      if ! Ask "Proceed and publish it anyway?"
+      then return 2
+      fi
+      return 0
+   elif [ "$status" -eq 2 ]
+   then
+      Log_Error "RecipeLint reported errors in $program $version from trunk. Not publishing it."
+      return 2
+   fi
+   return 1
+}
+
 function publish_revision() {
    program="$1"
    version="$2"
    
    if ! [ -d "$revisions/$program" ]
    then
-      svn mkdir "$revisions/$program"
+      mkdir "$revisions/$program"
    fi
    prefix="$version-r"
    if ls -d "$revisions/$program/$prefix"* &> /dev/null
@@ -90,34 +120,19 @@ function publish_revision() {
    Log_Normal "Publishing revision: $program $version-r$revision"
 
    unset publishrecipe
-   recipetarball="$goboTemp/$program--$version--recipe.tar.bz2"
-   (
-      cd "$trunk"
-      Verbose tar cjvpf "$recipetarball" --exclude=.svn "$program/$version"
-   )
 
-   if ! Boolean "skip-lint"
+   if Boolean "skip-lint"
    then
-      RecipeLint "$recipetarball"
-      recipestatus=$?
-      rm "$recipetarball"
-      if [ "$recipestatus" -eq 1 ]
-      then
-         Log_Error "RecipeLint reported warnings in $program $version from trunk."
-         if ! Ask "Proceed and publish it anyway?"
-         then return
-         fi
-         publishrecipe=yes
-      elif [ "$recipestatus" -eq 2 ]
-      then
-         Log_Error "RecipeLint reported errors in $program $version from trunk. Not publishing it."
-         return
-      fi
+      lint_recipe "$program" "$version"
+      case $? in
+      0) publishrecipe=yes ;;
+      1) : ;;
+      2) return ;;
+      esac # esac is ridiculous.
    fi
 
-   svn cleanup "$appdir"
-   Quiet svn update "$appdir"
-   svn copy "$appdir" "$revisions/$program/$version-r$revision"
+   mkdir -p "$revisions/$program"
+   cp -a "$appdir" "$revisions/$program/$version-r$revision"
    
    if [ `ls "$revisions/$program" | wc -l` -eq 1 ]
    then revdir="$revisions/$program"
@@ -125,16 +140,18 @@ function publish_revision() {
    fi
    
    Log_Normal "Listing $revdir"
-   find $revdir | grep -v '\.svn'
+   find $revdir
    if [ ! "$publishrecipe" ] && [ ! "$batch" ] && ! Ask "Ok to commit revision?"
    then 
-      # svn revert $revdir ?
       rm -rf $revdir
       return
    fi
    
    Log_Normal "Committing..."
-   svn commit $username --message "Committing revision $revision of $program $version" $revdir
+   Quiet pushd ${compileGitLocalRevisions}
+   git add $revdir
+   git commit -m "Revision $program $version-r$revision submitted by $compileRecipeAuthor" 
+   Quiet pushd ${compileGitLocalRevisions}
 }
 
 ### Operation #################################################################
@@ -142,54 +159,20 @@ function publish_revision() {
 program="$(basename $(Arg 1))"
 version="$(Arg 2)"
 
-trunk=`Get_Local_Trunk` || Die "Could not find a valid svn trunk."
+Check_Git_Tree || Die "Failed checking git tree."
+
+trunk=`Get_Local_Trunk` || Die "Could not find a valid git trunk."
 
 programintrunk=`ls "$trunk" | grep -i "^$program$"`
 [ "$programintrunk" ] || echo "Could not find $program in trunk."
 [ `echo "$programintrunk" | wc -l` -eq 1 ] || Die "More than one capitalization for $program found in trunk. Please check."
 program="$programintrunk"
 
-unset checkedout
-if ! revisions=`Get_Local_Revisions`
-then 
-   if Ask "You don't seem to have a copy of the svn revisions tree. Fetch it?"
-   then
-      Log_Normal "Calling 'svn checkout'."
-      mkdir -p ${compileSubversionLocalDir}
-      Quiet pushd ${compileSubversionLocalDir}
-      svn checkout --non-recursive $compileSubversionServerRepository/revisions || Die "Error doing the svn checkout."
-      Quiet popd
-      Log_Normal "Checkout finished."
-      checkedout=yes
-   fi
-   if ! revisions=`Get_Local_Revisions` || [ ! "$checkedout" ]
-   then Die "Could not find a valid svn revisions tree."
-   fi
-fi
+revisions=`Get_Local_Revisions`
 
-existingprogram=`ls "$revisions" 2> /dev/null | grep -i "^$program$"`
-if [ ! "$existingprogram" ]
-then
-   Log_Normal "Trying to checkout $program..."
-   Quiet pushd $revisions
-   svn checkout "$compileSubversionServerRepository/revisions/$program"
-   Quiet popd
-   checkedout=yes
-fi
-
-if [ ! "`ls "$trunk/$program"`" ]
-then
-   Log_Normal "No versions in trunk. Checking out..."
-   Quiet pushd $trunk
-   svn checkout "$compileSubversionServerRepository/trunk/$program"
-   Quiet popd
-fi
-
-if [ ! "$checkedout" = "yes" ]
-then
-   Log_Normal "Updating local subversion copy..."
-   svn update "$revisions/$program"
-fi
+Quiet pushd $revisions
+git pull
+Quiet popd
 
 if [ "$version" ]
 then
diff --git a/bin/PutRecipe b/bin/PutRecipe
--- a/bin/PutRecipe
+++ b/bin/PutRecipe
@@ -8,12 +8,12 @@ Import OptionParser
 Import Archive
 
 Parse_Conf Compile/Compile.conf
-Parse_Conf CompileSubversion.conf
-[ -z "${compileSubversionLocalDir}" ] && Die "You must run 'UpdateSettings develscripts' before trying to run PutRecipe again."
+Parse_Conf --mandatory CompileGit.conf
+[ "$compileGitServerRepository" ] || Die "Please check your CompileGit.conf configuration."
 
 ### Options ###################################################################
 
-scriptDescription="Put a recipe in the svn trunk/revision tree and upload it to the store."
+scriptDescription="Put a recipe in the git tree and upload it to the store."
 scriptCredits="Copyright (C) 2007 Lucas C. Villa Real. Released under the GNU GPL."
 helpOnNoArguments=yes
 scriptUsage="[ -m 'message' ] { <recipe dir> | <recipe name> [<recipe version>] }"
@@ -24,15 +24,6 @@ Add_Option_Boolean "" "batch" "Operate without prompting."
 Parse_Options "$@"
 
 ### Operation #################################################################
-
-[ "$compileLocalRecipesDir" ] || compileLocalRecipesDir="$goboData/Compile/LocalRecipes"
-mkdir -p "$compileLocalRecipesDir"
-[ "$compilePackedRecipesDir" ] || compilePackedRecipesDir="$goboData/Compile/PackedRecipes"
-mkdir -p "$compilePackedRecipesDir"
-[ "$compileSubversionLocalTrunk" ] || compileSubversionLocalTrunk="$goboData/Compile/Subversion/trunk"
-mkdir -p "$compileSubversionLocalTrunk"
-[ "$compileSubversionLocalRevisions" ] || compileSubversionLocalRevisions="$goboData/Compile/Subversion/revisions"
-mkdir -p "$compileSubversionLocalRevisions"
 
 if [ -z "$SVN_EDITOR" -a -z "$VISUAL" -a -z "$EDITOR" ]
 then
@@ -83,6 +74,10 @@ fi
 [ -r "$entry/$version/Recipe" ] || Die "Could not read Recipe file in $entry/$version."
 
 # Perform some simple cleanups
+postinstall="$entry/$version/Resources/PostInstall"
+if [ -e "$postinstall" ]
+then chmod +x "$postinstall"
+fi
 for i in `find $entry/$version -name Recipe`
 do
   [ -w `dirname "$i"` ] || Die "Need write permissions to the recipe."
@@ -114,25 +109,19 @@ tarball=${compilePackedRecipesDir}/${program}--${version}--recipe.tar.bz2
 
 version=`basename $tarball | sed 's,\(.*\)--\(.*\)--.*,\2,g'`
 # Merge the recipe into the local trunk
-ImportRecipe $(Boolean batch && echo "--batch") $tarball || exit 1
-
-contextlines=$(svn diff --non-interactive $compileSubversionLocalTrunk/$program/$version | wc -l)
+ImportRecipe $(Boolean batch && echo "--batch") $tarball || Die "Not publishing a revision."
 
 programlist="$program $programlist"
-if [ $contextlines -ne 0 ]
-then
-   # Commit the trunk and/or the revision tree.
-   if Is_Entry "message"
-   then PublishRevision $(Boolean batch && echo "--batch") --message "$(Entry "message")" --skip-lint $program $version || exit 1
-   else PublishRevision $(Boolean batch && echo "--batch") --skip-lint $program $version || exit 1
-   fi
-   postinstall=$program/$version/Resources/PostInstall
-   for localdir in $compileSubversionLocalTrunk $compileSubversionLocalRevisions
-   do
-       if [ -e $localdir/$postinstall ]
-       then svn propset svn:executable true $localdir/$postinstall
-       fi
-   done
-else
-   Log_Normal "No differences. Will not publish a revision."
+
+# Commit the trunk and/or the revision tree.
+if Is_Entry "message"
+then PublishRevision $(Boolean batch && echo "--batch") --message "$(Entry "message")" --skip-lint $program $version || exit 1
+else PublishRevision $(Boolean batch && echo "--batch") --skip-lint $program $version || exit 1
+fi
+Log_Normal "Pushing revision..."
+
+cd "$compileGitLocalTrunk"
+if git push
+then Log_Normal "Submitted $program $version."
+else Die "Failed submitting $program $version."
 fi
