Remove remnants of svn from PublishRevision

diff --git a/bin/PublishRevision b/bin/PublishRevision
--- a/bin/PublishRevision
+++ b/bin/PublishRevision
@@ -10,7 +10,7 @@ Import OptionParser
 
 ### Options ###################################################################
 
-scriptDescription="Publish a revision from the svn trunk to the revisions tree."
+scriptDescription="Publish a revision from the git trunk to the revisions tree."
 scriptCredits="Copyright (C) 2006 Hisham Muhammad. Released under the GNU GPL."
 helpOnNoArguments=yes
 scriptUsage="<program> [<version>]"
@@ -20,7 +20,7 @@ Add_Option_Boolean "S" "skip-lint" "Don't run RecipeLint."
 Add_Option_Boolean "b" "batch" "Don't ask questions. Generate automatic commit logs such as 'NewVersion' and 'New recipe'."
 #Add_Option_Entry "r" "rename" "Rename program to <entry>."
 #Add_Option_List "l" "list" "Enter a colon-separated list of..." "foo:bar"
-Add_Option_Entry "u" "username"  "User name used for committing changes at svn server."
+Add_Option_Entry "u" "username"  "User name used for committing changes at git server."
 Add_Option_Entry "m" "message" "Enter a commit message." ""
 Parse_Options "$@"
 
@@ -70,6 +70,10 @@ function lint_recipe() {
    return 1
 }
 
+function has_changes() {
+   ( cd "$1"; git status --porcelain | egrep -q "^( M|\?\?)" )
+}
+
 function publish_revision() {
    program="$1"
    version="$2"
@@ -84,8 +88,8 @@ function publish_revision() {
       latest=`cd "$revisions/$program"; ls -d "$prefix"* | cut -b$[${#prefix}+1]- | sort -nr | head -n1`
       revision=$[latest+1]
       revisiondir="$revisions/$program/$version-r$latest"
-      needs_commit=`svn status "$revisiondir" | grep -q ^A && echo "yes" || echo "no"`
-      if [ "$needs_commit" = "no" ] && [ `diff -Nur --exclude .svn "$revisiondir" "$trunk/$program/$version" | wc -l` = 0 ]
+      needs_commit=`has_changes "$revisiondir" && echo "yes" || echo "no"`
+      if has_changes "$revisiondir" && [ `diff -Nur "$revisiondir" "$trunk/$program/$version" | wc -l` = 0 ]
       then
          Log_Verbose "There are no differences between the trunk and the latest revision (r$latest)."
          Log_Verbose "Will not publish a new revision for $program $version."
@@ -98,7 +102,7 @@ function publish_revision() {
    fi
    
    appdir="$trunk/$program/$version"
-   if [ `svn status "$appdir" | wc -l` -gt 0 ]
+   if has_changes "$appdir"
    then
       Log_Normal "Trunk has uncommitted changes for $program $version."
       if [ `ls "$trunk/$program" | wc -l` -eq 1 ]
@@ -111,10 +115,15 @@ function publish_revision() {
       if Is_Entry "message"
       then commitmsg="$(Entry "message")"
       fi
-      if [ "$batch" ] || [ "$revision" = 1 ] || Is_Entry "message"
-      then svn commit -m "$commitmsg" $username "$commitdir" || Die "Error committing $commitdir"
-      else svn commit $username "$commitdir" || Die "Error committing $commitdir"
-      fi
+      pushd "$commitdir"
+      git add *
+      {
+         if [ "$batch" ] || [ "$revision" = 1 ] || Is_Entry "message"
+         then git commit $username -m "$commitmsg"
+         else git commit $username
+         fi
+      } || Die "Error committing $commitdir"
+      popd
    fi
    
    Log_Normal "Publishing revision: $program $version-r$revision"
